@Web_HostAddress = http://localhost:5231

GET {{Web_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Web_HostAddress}}/Name/
Accept: application/json

###
GET {{Web_HostAddress}}/Name1/
Accept: application/json
