<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\src\Ran.BackgroundJob\Ran.BackgroundJob.csproj" />
    <ProjectReference Include="..\..\..\..\framework\src\Ran.Ddd.EntityFramework\Ran.Ddd.EntityFramework.csproj" />
  </ItemGroup>
</Project>
