<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Ran.Basic.Application/Ran.Basic.Application.csproj" />
    <ProjectReference Include="../../src/Ran.Basic.AspNetCore/Ran.Basic.AspNetCore.csproj" />
    <ProjectReference Include="../../src/Ran.Basic.EntityFrameworkCore/Ran.Basic.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
