site_name: Ran.CleanArchitecture
site_url: https://tczy183.com/Ran.CleanArchitecture/
docs_dir: "content"
copyright: Copyright &copy; 2024 tczy183 # 左下角的版权声明

repo_name: "Ran.CleanArchitecture"
repo_url: "https://github.com/tczy183/Ran.CleanArchitecture"

nav:
  - 首页: index.md
  - 中文文档:
      - 入门
        - 创建项目: zh/quick-start/quick-start.md
  - English Docs:
      - Getting Started
        - Create Project: en/quick-start/quick-start.md

markdown_extensions:
  - attr_list # allows to add HTML/CSS attributes to almost every Markdown element, useful for e.g. aligning an image to the left/right (can't do centre though! use md_in_html instead)
  - md_in_html # allows to add markdown within HTML elements, useful for e.g. adding image captions or centering an image

  - pymdownx.betterem # Wider support to markdown symbols
  
  # Code syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed: # enables Content tabs.
      alternate_style: true
  - pymdownx.superfences # allows to add markdown to Content tabs. See https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#embedded-content

  # Mathjax support
  - pymdownx.arithmatex:
      generic: true

  # Call-outs and note boxes ('admonition')
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.instant #即时加载
    - navigation.tabs  #导航选项卡
    - navigation.tabs.sticky #粘性导航标签
    - navigation.sections #导航部分
    - navigation.expand #导航展开
    - navigation.prune #导航修剪
    - navigation.top #导航顶部
  language: zh
  theme:
    palette:

      # Palette toggle for automatic mode
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference

plugins:
  - search
  - awesome-pages # allows to customise the ordering of pages.
  - git-revision-date-localized: # Displays date created/modified on the page. The below configurations are bugged, so only date modified works.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tczy183
      name: tczy183 on Github