site_name: Ran.CleanArchitecture
docs_dir: "content"
copyright: Copyright &copy; 2024 zhangyang # 左下角的版权声明

repo_name: "GitHub"
repo_url: "https://github.com/tczy183/Ran.CleanArchitecture"

nav:
  - 首页: index.md
  - 入门:
      - 创建项目: started/getting-started.md
      - 项目结构: started/project-structure.md
      - 开发流程: started/development-process.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
      linenums: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: netcorepal
      repo: netcorepal-cloud-framework
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  features:
    - navigation.instant #即时加载
    - navigation.tabs  #导航选项卡
    - navigation.tabs.sticky #粘性导航标签
    - navigation.sections #导航部分
    - navigation.expand #导航展开
    - navigation.prune #导航修剪
    - navigation.top #导航顶部
  language: zh
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
